### ISSUE TITLE
Add browser side version

### ISSUE THREAD

**Issue by Bellisario** [nickpalenchar/goodtimer#35]
**Is your feature request related to a problem? Please describe.**
Can be a good thing add also a client version.

**Describe the solution you'd like**
Add the javascript client side version.

**Describe alternatives you've considered**
Now I can only use goodtimer with node js and not within a browser...

**Additional context**
/

**Comment by nickpalenchar** [comment]
Now available via cdn

https://github.com/nickpalenchar/goodtimer#-browser-compatible-client-side-version-now-available

https://cdn.nickpal.to/goodtimer/goodtimer-3.0.2.js

**Comment by Bellisario** [comment]
Thank you @nickpalenchar!
